services:
    front:
        build: ./front
        container_name: front
        ports:
            - "80:80"
        restart: unless-stopped
        depends_on:
            - back

    back:
        build: ./back
        env_file: ./back/.env
        expose:
            - "8000"
        depends_on:
            - redis
        restart: unless-stopped

    redis:
        image: redis:7
        command: ["redis-server", "--save", "60", "1"]
        restart: unless-stopped
