services:
    backend:
        build: ./back
        ports:
            - "8000:8000"
        depends_on:
            - redis

    agent:
        build: ./agent
        depends_on:
            - redis
        cap_add:
            - NET_RAW

    redis:
        image: redis:7
        ports:
            - "6379:6379"
