[project]
name = "back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.0",
    "redis>=7.0.0",
    "uuid>=1.30",
    "uvicorn>=0.38.0",
]
